[package]
name = "donation-abi"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.donation]
path = ".."

[dependencies.elrond-wasm]
version = "0.29.2"

[dependencies.elrond-wasm-debug]
version = "0.29.2"
